FROM balenalib/%%BALENA_MACHINE_NAME%%-ubuntu-python:3.8-bionic-build

# Set our working directory
WORKDIR /usr/src/app

#     
RUN pip3 install zeroconf

COPY *.py ./

# registration.py will run when container starts up on the device
CMD ["python3", "registration.py"]
# CMD ["/bin/bash"]